\\ CONFIGURAZIONE DEI REGISTRI GENERAL_PURPOSE E FUNZIONI SUI GPIO

HEX

\\ Indirizzo di base dei registri 7E000000
7E000000 CONSTANT BASE

\\ Alternate Function Select
BASE 200000 + CONSTANT GPFSEL0
BASE 200004 + CONSTANT GPFSEL1
BASE 200008 + CONSTANT GPFSEL2

\\ Pin Output Set
BASE 20001C + CONSTANT GPSET0

\\ Pin Output Clear
BASE 200028 + CONSTANT GPCLR0

\\ Pin Level
BASE 200034 + CONSTANT GPLEV0

\\ Event Detect Status
BASE 200040 + CONSTANT GPEDS0

\\ Falling Edge Detect Enable
BASE 200058 + CONSTANT GPFEN0

\\ Async. Rising Edge Detect
BASE 20007C + CONSTANT GPAREN0

: 2* 1 SWAP LSHIFT ;

: ON 2* GPSET0 ! ;

: OFF 2* GPCLR0 ! ;

: ISACTIVE GPLEV0 @ SWAP RSHIFT 1 AND ;

: DELAY BEGIN 1 - DUP 0 = UNTIL DROP ;

DECIMAL

\\ Controllo che il numero del pin GPIO inserito sia minore di 18 (per errori di definizione dell'operatore >), 
\\ altrimenti termina l'esecuzione e ripulisce lo stack.
: GPIO DUP 18 > IF ABORT THEN ;

\\ MODE (N -- R A B) R -> GPFSEL_REGISTER_ADDR; A -> PIN_ADDRESS B -> SPLACEMENT_BIT
\\ ES: 11 -- 2116026372 -1061109568 3

: MODE 10 /MOD 4 * GPFSEL0 + SWAP 3 * DUP 7 SWAP LSHIFT ROT DUP @ ROT INVERT AND ROT ;

: OUTPUT 1 SWAP LSHIFT OR SWAP ! ;

: INPUT 1 SWAP LSHIFT INVERT AND SWAP ! ;

