: ABS DUP 0< IF -1 * THEN ;
HEX
20000000 CONSTANT RPI1_BASE
: BILS 1 SWAP LSHIFT ;
: BIC INVERT AND ;
: ENABLE_PIN DUP >R @ -ROT >R BIC R> OR R> ! ;          
: DISABLE_PIN NIP DUP >R @ SWAP BIC R> ! ;
VARIABLE TIMES



RPI1_BASE 200000 +  CONSTANT GPIO_BASE
GPIO_BASE           CONSTANT GPFSEL0
GPIO_BASE 4 +       CONSTANT GPFSEL1

GPIO_BASE 1C +      CONSTANT GPSET0
GPIO_BASE 28 +      CONSTANT GPCLR0
GPIO_BASE 34 +      CONSTANT GPLEV0
RPI1_BASE 3000 +    CONSTANT SYSTEM_TIME_BASE
SYSTEM_TIME_BASE 4 + CONSTANT CLO_REGISTER
0                   CONSTANT INP
1                   CONSTANT OUT
DECIMAL
: MILLISECONDS 1000 * ;
: DELAY CLO_REGISTER @ BEGIN 2DUP CLO_REGISTER @ - ABS SWAP > UNTIL 2DROP ;
18 BILS             CONSTANT GPIO18
: N_GPIO 0 SWAP BEGIN DUP 2 MOD 0 = IF 1 RSHIFT SWAP 1+ SWAP ELSE THEN DUP 2 = UNTIL DROP 1+ ;
: MODE SWAP LSHIFT ;
: GPIO_LSB N_GPIO 10 MOD 3 * ;
: FSEL_MASK DUP DUP 2 + >R 1 + >R BILS 1 R> LSHIFT OR 1 R> LSHIFT OR ;
: FSEL GPIO_LSB DUP FSEL_MASK ;
: GPFSEL N_GPIO 10 / 4 * GPFSEL0 + ;
: GPSET N_GPIO 32 / 4 * GPSET0 + ;
: GPCLR N_GPIO 32 / 4 * GPCLR0 + ;
\ : GPLEV N_GPIO 32 / 4 * GPLEV0 + ;

: GET_GPLEV 32 / 4 * GPLEV0 + ;
: PIN_LEVEL DUP GET_GPLEV @ SWAP 32 MOD 1 SWAP LSHIFT AND IF 1 ELSE 0 THEN ;

-40                 CONSTANT MIN_TEMP
80                  CONSTANT MAX_TEMP
0                   CONSTANT MIN_HUM
100                 CONSTANT MAX_HUM

VARIABLE DATA
VARIABLE CHECKSUM

VARIABLE HUMIDITY_IP
VARIABLE HUMIDITY_DP
VARIABLE TEMPERATURE_IP
VARIABLE TEMPERATURE_DP

24 FSEL_MASK    CONSTANT GPIO18_FSEL
24 BILS         CONSTANT GPIO18_OUTPUT
0               CONSTANT GPIO18_INPUT

: WAIT_PULLDOWN BEGIN DUP PIN_LEVEL 0 = WHILE REPEAT DROP ;

: WAIT_PULLUP BEGIN DUP PIN_LEVEL 1 = WHILE REPEAT DROP ;

: SETUP_PIN OVER DUP FSEL -ROT MODE ROT GPFSEL ;

: DHT_OUT GPIO18_FSEL GPIO18_OUTPUT GPFSEL1 ENABLE_PIN ;

: DHT_INPUT GPIO18_FSEL GPIO18_INPUT GPFSEL1 ENABLE_PIN ;

: SETUP_SENSOR 
    DHT_OUT
    GPIO18 DUP GPCLR !
    1000 DELAY
    GPIO18 DUP GPSET !
    DHT_INPUT ;

: READ_BIT DUP WAIT_PULLDOWN CLO_REGISTER @ SWAP WAIT_PULLUP CLO_REGISTER @ SWAP - 50 > IF 1 ELSE 0 THEN ;

: READ_DATA 
    GPIO18 N_GPIO DUP DUP DUP WAIT_PULLDOWN WAIT_PULLUP
    39 BEGIN
        DUP 7 > IF
            DATA DUP @ 1 LSHIFT
        ELSE 
            CHECKSUM DUP @ 1 LSHIFT
        THEN
        3 PICK READ_BIT
        OR SWAP !
        1 - DUP 0 >
    WHILE REPEAT 2DROP ;

: GET_HUMIDITY 
    DATA @ 16 RSHIFT 10 /MOD DUP DUP MIN_HUM >= SWAP MAX_HUM <= AND
    IF
        HUMIDITY_IP ! 
        HUMIDITY_DP ! 
    ELSE
        2DROP
    THEN ;

: GET_TEMPERATURE 
    DATA @ 65535 AND 10 /MOD DUP DUP MIN_TEMP >= SWAP MAX_TEMP <= AND
    IF
        TEMPERATURE_IP !
        TEMPERATURE_DP !
    ELSE
        2DROP
    THEN ;

: GET_READING GET_HUMIDITY GET_TEMPERATURE ;

: HUMIDITY>CMD HUMIDITY_IP ? HUMIDITY_DP ? CR ;

: TEMPERATURE>CMD TEMPERATURE_IP ? TEMPERATURE_DP ? CR ;

: DHT>CMD TEMPERATURE>CMD HUMIDITY>CMD ;

: MEASURE 0 DATA ! 0 CHECKSUM ! SETUP_SENSOR READ_DATA GET_READING DHT>CMD ;
