
HEX

\ Costanti

GPIO25              CONSTANT FAN

FAN FSEL            CONSTANT FAN_FSEL
FAN OUT MODE        CONSTANT FAN_OUT
FAN GPFSEL          CONSTANT FAN_GPFSEL 

\ Word(s)

: FAN_PIN   FAN_FSEL FAN_OUT FAN_GPFSEL ;

: CONTROL_ACTUATOR GPSET0 GPCLR0 ;

\ FAN CONTROL_ACTUATOR ON
\ FAN CONTROL_ACTUATOR OFF

: INIT_FAN 
    FAN_PIN ENABLE_PIN ;

: FAN_OK 
    S" TEST-MODE" FIND NOT IF 
        CR ."           **********" CR
        ." led.f CARICATO CORRETTAMENTE" CR 
        ." SUCCESSIVAMENTE CARICARE i2c.f" CR 
        ." OK " CR
        ."           **********" CR
    THEN ;

FAN_OK

