180 CONSTANT FIRST_LINE
1C0 CONSTANT SECOND_LINE
FIRST_LINE 14 + CONSTANT THIRD_LINE
SECOND_LINE 14 + CONSTANT FOURTH_LINE

: CURSOR.RSHIFT 114 DISPLAY ;
: CURSOR.LSHIFT 110 DISPLAY ;

: HOME 102 DISPLAY ;

: CURSOR.OFF 10C DISPLAY ;
: CURSOR.BLINK.OFF 10E DISPLAY ;
: CURSOR.ON 10F DISPLAY ;

: SPACE 20 DISPLAY ;

: STAR 2A DISPLAY ;

: STARS
    BEGIN 
        STAR
        1 - DUP
    0 = UNTIL DROP ;

: SPACES
    BEGIN 
        SPACE
        1 - DUP
    0 = UNTIL DROP ;

: STARS_ROW
    3 STARS
    E SPACES
    3 STARS ;

: WELCOME
    57 DISPLAY
    65 DISPLAY
    6C DISPLAY
    63 DISPLAY
    6F DISPLAY
    6D DISPLAY
    65 DISPLAY ;

: TO 
    74 DISPLAY 
    6F DISPLAY ;

: FT 
    46 DISPLAY
    54 DISPLAY ;

: PROJECT 
    50 DISPLAY
    72 DISPLAY
    6F DISPLAY
    6A DISPLAY
    65 DISPLAY 
    63 DISPLAY
    74 DISPLAY ;

: PROJ_NAME 
    FT
    SPACE
    PROJECT ;

: CENTER_WELCOME 
    STAR
    4 SPACES
    WELCOME SPACE TO
    4 SPACES
    STAR ;

: CENTER_PROJ_NAME
    STAR
    4 SPACES
    PROJ_NAME
    4 SPACES
    STAR ;

: START_SCREEN_1 
    FIRST_LINE DISPLAY
    STARS_ROW
    SECOND_LINE DISPLAY
    CENTER_WELCOME
    THIRD_LINE DISPLAY
    CENTER_PROJ_NAME
    FOURTH_LINE DISPLAY
    STARS_ROW ;

: EMBEDDED 
    45 DISPLAY
    6D DISPLAY
    62 DISPLAY
    65 DISPLAY
    64 DISPLAY
    64 DISPLAY
    65 DISPLAY
    64 DISPLAY ;

: SYSTEMS
    53 DISPLAY
    79 DISPLAY
    73 DISPLAY
    74 DISPLAY
    65 DISPLAY
    6D DISPLAY
    73 DISPLAY ;

: SUBJECT 
    EMBEDDED SPACE SYSTEMS ;

: Y_2022 
    32 DISPLAY
    30 DISPLAY
    32 DISPLAY
    32 DISPLAY ;

: Y_2023
    32 DISPLAY
    30 DISPLAY
    32 DISPLAY
    33 DISPLAY ;

: COURSE.YEAR
    41 DISPLAY
    2E DISPLAY
    41 DISPLAY
    2E DISPLAY
    SPACE
    Y_2022
    2D DISPLAY
    Y_2023 ;

: CENTER_SUBJECT
    STAR SPACE
    SUBJECT SPACE
    STAR ;

: CENTER_COURSE_YEAR
    STAR 2 SPACES
    COURSE.YEAR 2 SPACES
    STAR ;

: START_SCREEN_2
    SECOND_LINE DISPLAY
    CENTER_SUBJECT
    THIRD_LINE DISPLAY
    CENTER_COURSE_YEAR ;

: FARDELLA.NAME
    56 DISPLAY 69 DISPLAY 6E DISPLAY 63 DISPLAY 65 DISPLAY 6E DISPLAY 7A DISPLAY 6F DISPLAY 
    SPACE 
    46 DISPLAY 61 DISPLAY 72 DISPLAY 64 DISPLAY 65 DISPLAY 6C DISPLAY 6C DISPLAY 61 DISPLAY ;

: FARDELLA.ID 
    4D DISPLAY 61 DISPLAY 74 DISPLAY 72 DISPLAY 2E DISPLAY
    SPACE
    30 DISPLAY 37 DISPLAY 33 DISPLAY 38 DISPLAY 30 DISPLAY 34 DISPLAY 35 DISPLAY ;

: START_SCREEN_3
    SECOND_LINE DISPLAY
    SPACE FARDELLA.NAME 2 SPACES
    THIRD_LINE DISPLAY
    3 SPACES FARDELLA.ID 4 SPACES ;

: TORTORICI.NAME
    4D DISPLAY 61 DISPLAY 72 DISPLAY 69 DISPLAY 6F DISPLAY
    SPACE
    54 DISPLAY 6F DISPLAY 72 DISPLAY 74 DISPLAY 6F DISPLAY 72 DISPLAY 69 DISPLAY 63 DISPLAY 69 DISPLAY ;

: TORTORICI.ID
    4D DISPLAY 61 DISPLAY 74 DISPLAY 72 DISPLAY 2E DISPLAY
    SPACE
    30 DISPLAY 37 DISPLAY 33 DISPLAY 37 DISPLAY 38 DISPLAY 39 DISPLAY 32 DISPLAY ;

: START_SCREEN_4
    SECOND_LINE DISPLAY
    2 SPACES TORTORICI.NAME 2 SPACES
    THIRD_LINE DISPLAY
    3 SPACES TORTORICI.ID 4 SPACES ;

: START_SCREEN
    101 DISPLAY
    START_SCREEN_1
    80 MS
    START_SCREEN_2
    80 MS
    START_SCREEN_3
    80 MS
    START_SCREEN_4 
    80 MS
    101 DISPLAY ;